language: node_js
node_js:
- '5'
- '4.2'
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    repo: simbo/gulp-watchify-browserify
after_script:
- npm run cover
- npm run codecov
sudo: false
env:
  global:
    secure: WuFgPFq0rdZ413nQvGjIGbW7XxH/SFpTBoYHoJWokoQ2clsseSgQam27Ljxqoy/Fyf4C6MXqcNWhspR4xXxmD7B/SGUSXI4lEyoJYwkxokWtG7+op6KFsDZRkCRZMhytqmGX8TlBuKKEes8OGAA5SzAo0AfgaEFIfbp7dHGr7KdQI+4DORnTz2IlLphMlAPJRaIMGQonkD4oTQqd7f94jrDKl5xp0n25I/buBXpTpbzn4EnBtIO6YZnNGCscAJ+KZbuYMFnGgt5aAuf+rkc+MSWWXPJzAPLZbX2xhWW5TIzLYQ/u/Ch96gSkxhMDnbiIt8ECeHSh9S9oPegzRb0RRd7y2UHPsaCy5Kc8wtjPbH79Pj8LuDKLhhgPsFOUIZyHVJ4ecvmTpmk8ae55oPPWL7vlqddJJeoe1RlUCYgi3xhq7iK7FKULo94tlbnTj/Y7M6r3Cl+yjIbzxoQTa/+2MITpHcHyiTzzT4BZukD/SPkVmXApdT3HAIsgMF06skxlR8GnIWPC855yRUveM2ep5wGYF/BnxJLyt5vUIzi3YneACZ14l+EkV75IYPTjMGcvukMP+wfXFZTbvH9QHOSUjHC57qIXfNQcSCTYH4Q/BAAzW2TFh6OzGUcheENRoeeOxeHOncilRIfs3zgVH3SaQdUWtlOsaAi+ErBdMdy6lIE=
